language: java
jdk: oraclejdk8
sudo: false
script: mvn clean install
notifications:
  slack:
    secure: puIeKqVwO2KRVuis91J9oOTplXzaplCX9C6QiHPsW+AMZ3Ywjfs4KJY2DJ8YXad1XIV/LeHtt8AmlB09005suS61KoTY504TEizrJVASi4K+vt78DQW3cePqPcYjB+Bq4fFmU12hsjhdHi4QKMfjhoYA25IQpZFOvPzwyx/V48fcN+xjU55l+GIAcKQu2Zp94sC+zCs1N07qzKe5j/iNcT2z/Rvw/3yfbNWqRuIyrrprDAWamEeKOL5UvA1VbiIwk3okku9tfFL+/fYiQx/8O1Fep7qNHClqTQtiB1GPiYAUZbkG9nWYSmBOKz3UuVxinrzTQ2hdCOHj4piAoXyv7C4gLv8C5NtHn5pom2v/slxG4VzBnsWYor+sF7AKmS16e4SoEnzlDOsNPZYRdEYOTd4T7HMNblFEA+fs+G88GdoCEM+NJ25nwpCFMsoLURLSKFWpAczcj3nI8b9x5xB5gQG2ck5+hFtgsBeIAnVr4VOCBU590R5lke7SmcZVi9px5Mvht8dmVX+fVccAwR7GBZ2VmQK01ATsHTzcPSeBHTIPTcZWSA3UE+NwdRMLM/xI5fMYgoZ318b8Ykk6oxobVf5V0YedCPlgHrEKCmMA2j+/SXdemZKZSjFLXEHpmKhjJrFBLp9UQToF3idLxS5KlO6yYIQWBN/TSdVwS925Y/0=
